version: 2

sources:
  - name: postgres
    schema: public
    tables:
      - name: commodities
        description: "Tabela que contém dados históricos das commodities"
        columns:
          - name: Date
            description: "Data da observação"
          - name: Close
            description: "Preço do fechamento da commodity"
          - name: simbolo
            description: "Símbolo da commodity"
      - name: movimentacao_commodities
        description: "Tabela seed"
        columns:
          - name: date
            description: "Data da transacao"
          - name: symbol
            description: "Símbolo da commodity"
          - name: action
            description: "Tipo de transação (buy/sell)"
          - name: quantity
            description: "Quantidade transacionada"